### ISSUE TITLE
[Bug]: No publishable resources for tag [laravel-advanced-string-config]

### ISSUE THREAD

**Issue by ghost** [mpstenson/laravel-advanced-string#3]
### What happened?

I run `php artisan vendor:publish --tag="laravel-advanced-string-config"`, as per the documentation steps, but I've got an INFO message: "No publishable resources for tag [laravel-advanced-string-config]" and no config file is present.

### How to reproduce the bug

I've just followed the installation steps: 

- [mpstenson/laravel-advanced-string package](https://github.com/mpstenson/laravel-advanced-string?tab=readme-ov-file#installation)
- I run `php artisan vendor:publish --tag="laravel-advanced-string-config"`, but I've got an INFO message: "No publishable resources for tag [laravel-advanced-string-config]" and no config file is present

### Package Version

1.0.0

### PHP Version

8.3

### Laravel Version

11.18.1

### Which operating systems does with happen with?

Windows

**Comment by mpstenson** [comment]
I'll be traveling for the next few days. I'll follow up when I have a chance to look.

**Comment by ghost** [comment]
> I'll be traveling for the next few days. I'll follow up when I have a chance to look.

Sure! There's no hurry! It's just a small mismatch, not a big concern. Other than that, congratulations for this idea! I really love it! I've been always a fan of "generating secure things", or better say - "strings" 😄👍
